name: 📚 Documentation
description: Report a documentation issue or suggest improvements
title: "[Docs]: "
labels: ["documentation", "triage"]
assignees:
  - TURPINJonathan

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation!

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - README.md
        - CONTRIBUTING.md
        - Code comments
        - Example/Tutorial
        - API reference
        - Other
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What kind of documentation issue?
      options:
        - Missing information
        - Incorrect/Outdated information
        - Unclear explanation
        - Typo/Grammar
        - Improvement suggestion
        - New documentation needed
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Location
      description: Where is the documentation issue located?
      placeholder: |
        File: README.md
        Section: Installation
        Line: 42
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current Documentation
      description: What does the current documentation say?
      placeholder: Quote or describe the current text...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: What should it say instead?
      placeholder: Your suggested text or improvement...
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason for Change
      description: Why is this change needed?
      placeholder: This would help users by...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots
      placeholder: Any additional information...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I am willing to submit a PR to fix this
          required: false
